export interface SystemTheme {
  id: string;
  name: string;
  mode: 'dark' | 'light';
  category: 'Assinatura' | 'Light Pro' | 'Dark Futurista' | 'Tons Frios' | 'Tons Quentes' | 'Neon & Retrô' | 'Minimalista';
  description: string;
  previewColors: {
    primary: string;
    accent: string;
    bg: string;
    surface: string;
  };
  variables: {
    '--brand-primary': string;
    '--brand-primary-hover': string;
    '--brand-primary-glow': string;
    '--border-focus': string;
    '--border-subtle'?: string;
    '--border-card'?: string;
    '--border-highlight'?: string;
    '--bg-main': string;
    '--bg-surface': string;
    '--bg-surface-elevated': string;
    '--bg-surface-hover': string;
    '--bg-card': string;
    '--text-primary': string;
    '--text-secondary': string;
    '--text-muted': string;
    '--shadow-glow'?: string;
  };
}

export const SYSTEM_THEMES: SystemTheme[] = [
  // ==========================================
  // 1. TEMAS CLAROS (LIGHT MODE)
  // ==========================================
  {
    id: 'bambu-light-official',
    name: 'Bambu Studio Clean',
    mode: 'light',
    category: 'Assinatura',
    description: 'Visual oficial claro com verde esmeralda vibrante e fundo branco neve perolado.',
    previewColors: {
      primary: '#10b981',
      accent: '#06b6d4',
      bg: '#f8fafc',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#10b981',
      '--brand-primary-hover': '#059669',
      '--brand-primary-glow': 'rgba(16, 185, 129, 0.25)',
      '--border-focus': '#10b981',
      '--border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--border-card': 'rgba(0, 0, 0, 0.09)',
      '--border-highlight': 'rgba(0, 0, 0, 0.16)',
      '--bg-main': '#f8fafc',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f1f5f9',
      '--bg-surface-hover': '#e2e8f0',
      '--bg-card': '#ffffff',
      '--text-primary': '#0f172a',
      '--text-secondary': '#475569',
      '--text-muted': '#94a3b8',
      '--shadow-glow': '0 0 20px rgba(16, 185, 129, 0.2)',
    },
  },
  {
    id: 'nordic-snow-light',
    name: 'Nordic Snow (Neve Ártica)',
    mode: 'light',
    category: 'Light Pro',
    description: 'Inspirado no design escandinavo minimalista, com azul ártico sobre branco puro.',
    previewColors: {
      primary: '#0284c7',
      accent: '#38bdf8',
      bg: '#f0f9ff',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#0284c7',
      '--brand-primary-hover': '#0369a1',
      '--brand-primary-glow': 'rgba(2, 132, 199, 0.25)',
      '--border-focus': '#0284c7',
      '--border-subtle': 'rgba(2, 132, 199, 0.12)',
      '--border-card': 'rgba(2, 132, 199, 0.15)',
      '--border-highlight': 'rgba(2, 132, 199, 0.25)',
      '--bg-main': '#f0f9ff',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#e0f2fe',
      '--bg-surface-hover': '#bae6fd',
      '--bg-card': '#ffffff',
      '--text-primary': '#0c4a6e',
      '--text-secondary': '#0369a1',
      '--text-muted': '#38bdf8',
      '--shadow-glow': '0 0 20px rgba(2, 132, 199, 0.2)',
    },
  },
  {
    id: 'paper-white-light',
    name: 'Modern Paper (Notion Style)',
    mode: 'light',
    category: 'Minimalista',
    description: 'Estética de papel off-white com tipografia grafite nítida e preto de alto contraste.',
    previewColors: {
      primary: '#18181b',
      accent: '#10b981',
      bg: '#fafafa',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#18181b',
      '--brand-primary-hover': '#27272a',
      '--brand-primary-glow': 'rgba(24, 24, 27, 0.2)',
      '--border-focus': '#18181b',
      '--border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--border-card': 'rgba(0, 0, 0, 0.1)',
      '--border-highlight': 'rgba(0, 0, 0, 0.2)',
      '--bg-main': '#fafafa',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f4f4f5',
      '--bg-surface-hover': '#e4e4e7',
      '--bg-card': '#ffffff',
      '--text-primary': '#09090b',
      '--text-secondary': '#52525b',
      '--text-muted': '#a1a1aa',
      '--shadow-glow': '0 0 15px rgba(0, 0, 0, 0.1)',
    },
  },
  {
    id: 'solar-day-light',
    name: 'Solar Day (Luz do Dia)',
    mode: 'light',
    category: 'Tons Quentes',
    description: 'Dourado âmbar e bronze quente sobre fundo marfim ensolarado.',
    previewColors: {
      primary: '#d97706',
      accent: '#ea580c',
      bg: '#fffbeb',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#d97706',
      '--brand-primary-hover': '#b45309',
      '--brand-primary-glow': 'rgba(217, 119, 6, 0.25)',
      '--border-focus': '#d97706',
      '--border-subtle': 'rgba(217, 119, 6, 0.12)',
      '--border-card': 'rgba(217, 119, 6, 0.15)',
      '--border-highlight': 'rgba(217, 119, 6, 0.25)',
      '--bg-main': '#fffbeb',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#fef3c7',
      '--bg-surface-hover': '#fde68a',
      '--bg-card': '#ffffff',
      '--text-primary': '#78350f',
      '--text-secondary': '#92400e',
      '--text-muted': '#b45309',
      '--shadow-glow': '0 0 20px rgba(217, 119, 6, 0.2)',
    },
  },
  {
    id: 'lavender-breeze-light',
    name: 'Lavender Breeze (Lavanda)',
    mode: 'light',
    category: 'Light Pro',
    description: 'Tons lilás e violeta suaves sobre branco pérola, suave e aconchegante.',
    previewColors: {
      primary: '#7c3aed',
      accent: '#ec4899',
      bg: '#faf5ff',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#7c3aed',
      '--brand-primary-hover': '#6d28d9',
      '--brand-primary-glow': 'rgba(124, 58, 237, 0.25)',
      '--border-focus': '#7c3aed',
      '--border-subtle': 'rgba(124, 58, 237, 0.12)',
      '--border-card': 'rgba(124, 58, 237, 0.15)',
      '--border-highlight': 'rgba(124, 58, 237, 0.25)',
      '--bg-main': '#faf5ff',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f3e8ff',
      '--bg-surface-hover': '#e9d5ff',
      '--bg-card': '#ffffff',
      '--text-primary': '#4c1d95',
      '--text-secondary': '#6d28d9',
      '--text-muted': '#a78bfa',
      '--shadow-glow': '0 0 20px rgba(124, 58, 237, 0.2)',
    },
  },
  {
    id: 'ocean-morning-light',
    name: 'Ocean Morning (Azul Mar)',
    mode: 'light',
    category: 'Tons Frios',
    description: 'Azul cobalto corporativo com fundo cinza gelo de alta legibilidade.',
    previewColors: {
      primary: '#2563eb',
      accent: '#06b6d4',
      bg: '#f1f5f9',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#2563eb',
      '--brand-primary-hover': '#1d4ed8',
      '--brand-primary-glow': 'rgba(37, 99, 235, 0.25)',
      '--border-focus': '#2563eb',
      '--border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--border-card': 'rgba(0, 0, 0, 0.1)',
      '--border-highlight': 'rgba(0, 0, 0, 0.18)',
      '--bg-main': '#f1f5f9',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#e2e8f0',
      '--bg-surface-hover': '#cbd5e1',
      '--bg-card': '#ffffff',
      '--text-primary': '#0f172a',
      '--text-secondary': '#334155',
      '--text-muted': '#64748b',
      '--shadow-glow': '0 0 20px rgba(37, 99, 235, 0.2)',
    },
  },
  {
    id: 'rose-champagne-light',
    name: 'Rose Champagne (Rosé)',
    mode: 'light',
    category: 'Tons Quentes',
    description: 'Rosa pálido com champanhe e ouro rosé, ideal para decoração e casamentos.',
    previewColors: {
      primary: '#e11d48',
      accent: '#f59e0b',
      bg: '#fff1f2',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#e11d48',
      '--brand-primary-hover': '#be123c',
      '--brand-primary-glow': 'rgba(225, 29, 72, 0.25)',
      '--border-focus': '#e11d48',
      '--border-subtle': 'rgba(225, 29, 72, 0.12)',
      '--border-card': 'rgba(225, 29, 72, 0.15)',
      '--border-highlight': 'rgba(225, 29, 72, 0.25)',
      '--bg-main': '#fff1f2',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#ffe4e6',
      '--bg-surface-hover': '#fecdd3',
      '--bg-card': '#ffffff',
      '--text-primary': '#881337',
      '--text-secondary': '#9f1239',
      '--text-muted': '#be123c',
      '--shadow-glow': '0 0 20px rgba(225, 29, 72, 0.2)',
    },
  },
  {
    id: 'mint-dew-light',
    name: 'Mint Dew (Orvalho de Menta)',
    mode: 'light',
    category: 'Tons Frios',
    description: 'Menta fresca e verde água sobre fundo branco perolado, revigorante.',
    previewColors: {
      primary: '#0d9488',
      accent: '#10b981',
      bg: '#f0fdfa',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#0d9488',
      '--brand-primary-hover': '#0f766e',
      '--brand-primary-glow': 'rgba(13, 148, 136, 0.25)',
      '--border-focus': '#0d9488',
      '--border-subtle': 'rgba(13, 148, 136, 0.12)',
      '--border-card': 'rgba(13, 148, 136, 0.15)',
      '--border-highlight': 'rgba(13, 148, 136, 0.25)',
      '--bg-main': '#f0fdfa',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#ccfbf1',
      '--bg-surface-hover': '#99f6e4',
      '--bg-card': '#ffffff',
      '--text-primary': '#134e4a',
      '--text-secondary': '#115e59',
      '--text-muted': '#14b8a6',
      '--shadow-glow': '0 0 20px rgba(13, 148, 136, 0.2)',
    },
  },
  {
    id: 'sunset-peach-light',
    name: 'Sunset Peach (Pêssego)',
    mode: 'light',
    category: 'Tons Quentes',
    description: 'Coral pêssego acolhedor com luminosidade natural e alta simpatia.',
    previewColors: {
      primary: '#ea580c',
      accent: '#f43f5e',
      bg: '#fff7ed',
      surface: '#ffffff',
    },
    variables: {
      '--brand-primary': '#ea580c',
      '--brand-primary-hover': '#c2410c',
      '--brand-primary-glow': 'rgba(234, 88, 12, 0.25)',
      '--border-focus': '#ea580c',
      '--border-subtle': 'rgba(234, 88, 12, 0.12)',
      '--border-card': 'rgba(234, 88, 12, 0.15)',
      '--border-highlight': 'rgba(234, 88, 12, 0.25)',
      '--bg-main': '#fff7ed',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#ffedd5',
      '--bg-surface-hover': '#fed7aa',
      '--bg-card': '#ffffff',
      '--text-primary': '#7c2d12',
      '--text-secondary': '#9a3412',
      '--text-muted': '#ea580c',
      '--shadow-glow': '0 0 20px rgba(234, 88, 12, 0.2)',
    },
  },
  {
    id: 'titanium-pure-light',
    name: 'Titanium Pure (Apple White)',
    mode: 'light',
    category: 'Minimalista',
    description: 'Cinza platina e titânio acetinado sobre branco absoluto estilo Apple Store.',
    previewColors: {
      primary: '#475569',
      accent: '#0284c7',
      bg: '#ffffff',
      surface: '#f8fafc',
    },
    variables: {
      '--brand-primary': '#475569',
      '--brand-primary-hover': '#334155',
      '--brand-primary-glow': 'rgba(71, 85, 105, 0.2)',
      '--border-focus': '#475569',
      '--border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--border-card': 'rgba(0, 0, 0, 0.1)',
      '--border-highlight': 'rgba(0, 0, 0, 0.18)',
      '--bg-main': '#ffffff',
      '--bg-surface': '#f8fafc',
      '--bg-surface-elevated': '#f1f5f9',
      '--bg-surface-hover': '#e2e8f0',
      '--bg-card': '#f8fafc',
      '--text-primary': '#0f172a',
      '--text-secondary': '#334155',
      '--text-muted': '#64748b',
      '--shadow-glow': '0 0 15px rgba(0, 0, 0, 0.08)',
    },
  },

  // ==========================================
  // 2. TEMAS ESCUROS (DARK MODE)
  // ==========================================
  {
    id: 'bambu-emerald',
    name: 'Bambu Emerald (Padrão)',
    mode: 'dark',
    category: 'Assinatura',
    description: 'Verde esmeralda oficial com fundo grafite profundo e acentos tecnológicos.',
    previewColors: {
      primary: '#10b981',
      accent: '#06b6d4',
      bg: '#06090e',
      surface: '#0c121e',
    },
    variables: {
      '--brand-primary': '#10b981',
      '--brand-primary-hover': '#059669',
      '--brand-primary-glow': 'rgba(16, 185, 129, 0.35)',
      '--border-focus': '#10b981',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#06090e',
      '--bg-surface': '#0c121e',
      '--bg-surface-elevated': '#131c2e',
      '--bg-surface-hover': '#1a263d',
      '--bg-card': 'rgba(16, 24, 40, 0.68)',
      '--text-primary': '#f8fafc',
      '--text-secondary': '#94a3b8',
      '--text-muted': '#64748b',
      '--shadow-glow': '0 0 25px rgba(16, 185, 129, 0.25)',
    },
  },
  {
    id: 'pure-oled',
    name: 'Deep Obsidian (Preto OLED)',
    mode: 'dark',
    category: 'Minimalista',
    description: 'Preto puro absoluto para telas OLED, com acentos brancos de alto contraste.',
    previewColors: {
      primary: '#10b981',
      accent: '#e2e8f0',
      bg: '#000000',
      surface: '#090909',
    },
    variables: {
      '--brand-primary': '#10b981',
      '--brand-primary-hover': '#059669',
      '--brand-primary-glow': 'rgba(16, 185, 129, 0.2)',
      '--border-focus': '#10b981',
      '--border-subtle': 'rgba(255, 255, 255, 0.08)',
      '--border-card': 'rgba(255, 255, 255, 0.1)',
      '--border-highlight': 'rgba(255, 255, 255, 0.2)',
      '--bg-main': '#000000',
      '--bg-surface': '#090909',
      '--bg-surface-elevated': '#141414',
      '--bg-surface-hover': '#202020',
      '--bg-card': 'rgba(10, 10, 10, 0.85)',
      '--text-primary': '#ffffff',
      '--text-secondary': '#a1a1aa',
      '--text-muted': '#71717a',
      '--shadow-glow': '0 0 15px rgba(255, 255, 255, 0.1)',
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon (Cyberpunk)',
    mode: 'dark',
    category: 'Neon & Retrô',
    description: 'Verde fluorescente de alta voltagem com toques de magenta e alta atitude.',
    previewColors: {
      primary: '#00ff9d',
      accent: '#ff007f',
      bg: '#040711',
      surface: '#090e1f',
    },
    variables: {
      '--brand-primary': '#00ff9d',
      '--brand-primary-hover': '#00d684',
      '--brand-primary-glow': 'rgba(0, 255, 157, 0.45)',
      '--border-focus': '#00ff9d',
      '--border-subtle': 'rgba(0, 255, 157, 0.12)',
      '--border-card': 'rgba(0, 255, 157, 0.15)',
      '--border-highlight': 'rgba(0, 255, 157, 0.3)',
      '--bg-main': '#040711',
      '--bg-surface': '#090e1f',
      '--bg-surface-elevated': '#101933',
      '--bg-surface-hover': '#182447',
      '--bg-card': 'rgba(9, 14, 31, 0.75)',
      '--text-primary': '#f0fdf4',
      '--text-secondary': '#86efac',
      '--text-muted': '#4ade80',
      '--shadow-glow': '0 0 30px rgba(0, 255, 157, 0.35)',
    },
  },
  {
    id: 'midnight-sapphire',
    name: 'Midnight Sapphire',
    mode: 'dark',
    category: 'Tons Frios',
    description: 'Azul celeste sobre fundo marinho escuro. Elegante e corporativo.',
    previewColors: {
      primary: '#38bdf8',
      accent: '#6366f1',
      bg: '#050b14',
      surface: '#0b1424',
    },
    variables: {
      '--brand-primary': '#38bdf8',
      '--brand-primary-hover': '#0ea5e9',
      '--brand-primary-glow': 'rgba(56, 189, 248, 0.35)',
      '--border-focus': '#38bdf8',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#050b14',
      '--bg-surface': '#0b1424',
      '--bg-surface-elevated': '#122038',
      '--bg-surface-hover': '#1a2e4d',
      '--bg-card': 'rgba(11, 20, 36, 0.72)',
      '--text-primary': '#f8fafc',
      '--text-secondary': '#93c5fd',
      '--text-muted': '#60a5fa',
      '--shadow-glow': '0 0 25px rgba(56, 189, 248, 0.25)',
    },
  },
  {
    id: 'royal-amethyst',
    name: 'Royal Amethyst',
    mode: 'dark',
    category: 'Dark Futurista',
    description: 'Roxo violeta profundo com atmosfera mística para colecionáveis.',
    previewColors: {
      primary: '#a855f7',
      accent: '#ec4899',
      bg: '#0a0614',
      surface: '#130d24',
    },
    variables: {
      '--brand-primary': '#a855f7',
      '--brand-primary-hover': '#9333ea',
      '--brand-primary-glow': 'rgba(168, 85, 247, 0.35)',
      '--border-focus': '#a855f7',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0a0614',
      '--bg-surface': '#130d24',
      '--bg-surface-elevated': '#1e1438',
      '--bg-surface-hover': '#2a1c4d',
      '--bg-card': 'rgba(19, 13, 36, 0.72)',
      '--text-primary': '#faf5ff',
      '--text-secondary': '#d8b4fe',
      '--text-muted': '#a855f7',
      '--shadow-glow': '0 0 25px rgba(168, 85, 247, 0.3)',
    },
  },
  {
    id: 'solar-amber',
    name: 'Solar Amber (Forja)',
    mode: 'dark',
    category: 'Tons Quentes',
    description: 'Dourado âmbar industrial quente para manufatura de precisão.',
    previewColors: {
      primary: '#f59e0b',
      accent: '#ea580c',
      bg: '#0d0904',
      surface: '#171107',
    },
    variables: {
      '--brand-primary': '#f59e0b',
      '--brand-primary-hover': '#d97706',
      '--brand-primary-glow': 'rgba(245, 158, 11, 0.35)',
      '--border-focus': '#f59e0b',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0d0904',
      '--bg-surface': '#171107',
      '--bg-surface-elevated': '#241a0b',
      '--bg-surface-hover': '#332510',
      '--bg-card': 'rgba(23, 17, 7, 0.75)',
      '--text-primary': '#fffbeb',
      '--text-secondary': '#fde68a',
      '--text-muted': '#d97706',
      '--shadow-glow': '0 0 25px rgba(245, 158, 11, 0.28)',
    },
  },
  {
    id: 'obsidian-crimson',
    name: 'Crimson Forge (Laser)',
    mode: 'dark',
    category: 'Tons Quentes',
    description: 'Carmesim marcante com preto carvão, inspirado no corte a laser.',
    previewColors: {
      primary: '#f43f5e',
      accent: '#fb923c',
      bg: '#0c0507',
      surface: '#170a0e',
    },
    variables: {
      '--brand-primary': '#f43f5e',
      '--brand-primary-hover': '#e11d48',
      '--brand-primary-glow': 'rgba(244, 63, 94, 0.35)',
      '--border-focus': '#f43f5e',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0c0507',
      '--bg-surface': '#170a0e',
      '--bg-surface-elevated': '#240f17',
      '--bg-surface-hover': '#331520',
      '--bg-card': 'rgba(23, 10, 14, 0.75)',
      '--text-primary': '#fff1f2',
      '--text-secondary': '#fecdd3',
      '--text-muted': '#e11d48',
      '--shadow-glow': '0 0 25px rgba(244, 63, 94, 0.3)',
    },
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost (Glacial)',
    mode: 'dark',
    category: 'Tons Frios',
    description: 'Ciano gelo cristalino com atmosfera limpa de laboratório.',
    previewColors: {
      primary: '#06b6d4',
      accent: '#38bdf8',
      bg: '#040b12',
      surface: '#091522',
    },
    variables: {
      '--brand-primary': '#06b6d4',
      '--brand-primary-hover': '#0891b2',
      '--brand-primary-glow': 'rgba(6, 182, 212, 0.35)',
      '--border-focus': '#06b6d4',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#040b12',
      '--bg-surface': '#091522',
      '--bg-surface-elevated': '#102236',
      '--bg-surface-hover': '#18304c',
      '--bg-card': 'rgba(9, 21, 34, 0.72)',
      '--text-primary': '#ecfeff',
      '--text-secondary': '#a5f3fc',
      '--text-muted': '#06b6d4',
      '--shadow-glow': '0 0 25px rgba(6, 182, 212, 0.3)',
    },
  },
  {
    id: 'synthwave-80s',
    name: 'Synthwave 80s (Outrun)',
    mode: 'dark',
    category: 'Neon & Retrô',
    description: 'Rosa magenta neon e púrpura crepúsculo. Vibe nostálgica anos 80.',
    previewColors: {
      primary: '#ff2a85',
      accent: '#9d4edd',
      bg: '#0e0517',
      surface: '#1a0a2b',
    },
    variables: {
      '--brand-primary': '#ff2a85',
      '--brand-primary-hover': '#e01e72',
      '--brand-primary-glow': 'rgba(255, 42, 133, 0.45)',
      '--border-focus': '#ff2a85',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0e0517',
      '--bg-surface': '#1a0a2b',
      '--bg-surface-elevated': '#281140',
      '--bg-surface-hover': '#381859',
      '--bg-card': 'rgba(26, 10, 43, 0.75)',
      '--text-primary': '#fff0f7',
      '--text-secondary': '#f49ac2',
      '--text-muted': '#ff2a85',
      '--shadow-glow': '0 0 30px rgba(255, 42, 133, 0.4)',
    },
  },
  {
    id: 'forest-moss',
    name: 'Forest Moss (Musgo)',
    mode: 'dark',
    category: 'Assinatura',
    description: 'Verde lima orgânico com toques de folhagem profunda.',
    previewColors: {
      primary: '#84cc16',
      accent: '#10b981',
      bg: '#060a04',
      surface: '#0c1409',
    },
    variables: {
      '--brand-primary': '#84cc16',
      '--brand-primary-hover': '#65a30d',
      '--brand-primary-glow': 'rgba(132, 204, 22, 0.35)',
      '--border-focus': '#84cc16',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#060a04',
      '--bg-surface': '#0c1409',
      '--bg-surface-elevated': '#142010',
      '--bg-surface-hover': '#1e2e18',
      '--bg-card': 'rgba(12, 20, 9, 0.75)',
      '--text-primary': '#f7fee7',
      '--text-secondary': '#d9f99d',
      '--text-muted': '#65a30d',
      '--shadow-glow': '0 0 25px rgba(132, 204, 22, 0.3)',
    },
  },
  {
    id: 'electric-indigo',
    name: 'Electric Indigo (Linear)',
    mode: 'dark',
    category: 'Dark Futurista',
    description: 'Índigo digital ultramoderno inspirado em ferramentas pro.',
    previewColors: {
      primary: '#6366f1',
      accent: '#38bdf8',
      bg: '#070714',
      surface: '#0e0f26',
    },
    variables: {
      '--brand-primary': '#6366f1',
      '--brand-primary-hover': '#4f46e5',
      '--brand-primary-glow': 'rgba(99, 102, 241, 0.38)',
      '--border-focus': '#6366f1',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#070714',
      '--bg-surface': '#0e0f26',
      '--bg-surface-elevated': '#17193b',
      '--bg-surface-hover': '#212452',
      '--bg-card': 'rgba(14, 15, 38, 0.72)',
      '--text-primary': '#eef2ff',
      '--text-secondary': '#c7d2fe',
      '--text-muted': '#6366f1',
      '--shadow-glow': '0 0 25px rgba(99, 102, 241, 0.3)',
    },
  },
  {
    id: 'dracula-theme',
    name: 'Dracula Pro (Dark)',
    mode: 'dark',
    category: 'Neon & Retrô',
    description: 'Paleta gótica com roxo fosco e acentos verde fluorescente.',
    previewColors: {
      primary: '#bd93f9',
      accent: '#50fa7b',
      bg: '#0c0c14',
      surface: '#161624',
    },
    variables: {
      '--brand-primary': '#bd93f9',
      '--brand-primary-hover': '#a779eb',
      '--brand-primary-glow': 'rgba(189, 147, 249, 0.35)',
      '--border-focus': '#bd93f9',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0c0c14',
      '--bg-surface': '#161624',
      '--bg-surface-elevated': '#212136',
      '--bg-surface-hover': '#2d2d4a',
      '--bg-card': 'rgba(22, 22, 36, 0.75)',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#bd93f9',
      '--text-muted': '#6272a4',
      '--shadow-glow': '0 0 25px rgba(189, 147, 249, 0.3)',
    },
  },
  {
    id: 'monokai-matrix',
    name: 'Monokai Matrix',
    mode: 'dark',
    category: 'Neon & Retrô',
    description: 'Amarelo ouro com fundo de carbono puro dos makers.',
    previewColors: {
      primary: '#ffd866',
      accent: '#ff6188',
      bg: '#0c0c0d',
      surface: '#161618',
    },
    variables: {
      '--brand-primary': '#ffd866',
      '--brand-primary-hover': '#e6c35c',
      '--brand-primary-glow': 'rgba(255, 216, 102, 0.35)',
      '--border-focus': '#ffd866',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0c0c0d',
      '--bg-surface': '#161618',
      '--bg-surface-elevated': '#222226',
      '--bg-surface-hover': '#2f2f35',
      '--bg-card': 'rgba(22, 22, 24, 0.8)',
      '--text-primary': '#fcfcfa',
      '--text-secondary': '#ffd866',
      '--text-muted': '#727072',
      '--shadow-glow': '0 0 25px rgba(255, 216, 102, 0.28)',
    },
  },
  {
    id: 'imperial-gold',
    name: 'Imperial Gold (Ouro 24k)',
    mode: 'dark',
    category: 'Minimalista',
    description: 'Dourado nobre com fundos aristocráticos para joalheria.',
    previewColors: {
      primary: '#eab308',
      accent: '#ca8a04',
      bg: '#0a0803',
      surface: '#151105',
    },
    variables: {
      '--brand-primary': '#eab308',
      '--brand-primary-hover': '#ca8a04',
      '--brand-primary-glow': 'rgba(234, 179, 8, 0.35)',
      '--border-focus': '#eab308',
      '--border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--border-card': 'rgba(255, 255, 255, 0.09)',
      '--border-highlight': 'rgba(255, 255, 255, 0.16)',
      '--bg-main': '#0a0803',
      '--bg-surface': '#151105',
      '--bg-surface-elevated': '#221c09',
      '--bg-surface-hover': '#30280d',
      '--bg-card': 'rgba(21, 17, 5, 0.78)',
      '--text-primary': '#fefce8',
      '--text-secondary': '#fef08a',
      '--text-muted': '#ca8a04',
      '--shadow-glow': '0 0 25px rgba(234, 179, 8, 0.32)',
    },
  },
];

const THEME_STORAGE_KEY = 'bambu_system_theme_id';

export function applyTheme(themeId: string): void {
  const theme = SYSTEM_THEMES.find(t => t.id === themeId) || SYSTEM_THEMES[0];
  const root = document.documentElement;

  // Set mode attribute on HTML root
  root.setAttribute('data-theme-mode', theme.mode);

  // Apply CSS variables
  Object.entries(theme.variables).forEach(([key, val]) => {
    if (val) {
      root.style.setProperty(key, val);
    }
  });

  try {
    localStorage.setItem(THEME_STORAGE_KEY, theme.id);
  } catch (err) {
    console.error('Falha ao salvar tema no localStorage:', err);
  }
}

export function getCurrentThemeId(): string {
  try {
    const saved = localStorage.getItem(THEME_STORAGE_KEY);
    if (saved && SYSTEM_THEMES.some(t => t.id === saved)) {
      return saved;
    }
  } catch {
    // fallback
  }
  return SYSTEM_THEMES[0].id;
}

export function initSystemTheme(): void {
  const current = getCurrentThemeId();
  applyTheme(current);
}
